package net.zimi.revisited.mixin.mixins.Common.Handler.Loot;

import deci.aD.a;
import deci.aD.k;
import deci.aD.l;
import java.util.ArrayList;
import java.util.HashMap;

import net.minecraft.block.Block;
import net.minecraft.item.ItemStack;
import net.zimi.revisited.Addon;
import org.spongepowered.asm.mixin.*;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.ModifyArg;

@Mixin(value = {l.class}, remap = false)
public abstract class LootRegistry implements a {

    @Final
    @Shadow
    private HashMap<Block, deci.aB.c> afq;

    @ModifyArg(method = {"gh"}, at = @At(value = "INVOKE", target = "Ldeci/aD/l$a;<init>(Lnet/minecraft/block/Block;ILjava/util/ArrayList;)V", ordinal = 25), index = 2)
    public ArrayList<ItemStack> setNewSupplyDropStack(ArrayList<ItemStack> arrayList) {
        return decimixin$supplyDropStack();
    }

    @ModifyArg(method = {"gh"}, at = @At(value = "INVOKE", target = "Ldeci/aD/l$a;<init>(Lnet/minecraft/block/Block;ILjava/util/ArrayList;)V", ordinal = 18), index = 2)
    public ArrayList<ItemStack> setNewMilitaryCrateStack(ArrayList<ItemStack> arrayList) {
        return decimixin$militaryCrateStack();
    }

    @ModifyArg(method = {"gh"}, at = @At(value = "INVOKE", target = "Ldeci/aD/l$a;<init>(Lnet/minecraft/block/Block;ILjava/util/ArrayList;)V", ordinal = 30), index = 2)
    public ArrayList<ItemStack> setNewMedicalCrateStack(ArrayList<ItemStack> arrayList) {
        return decimixin$medicalCrateStack();
    }

    @Unique
    private ArrayList<ItemStack> decimixin$medicalCrateStack() {
        ArrayList<ItemStack> list = new ArrayList<>(20);
        list.add(new ItemStack(k.ame, 2));
        list.add(new ItemStack(k.alY, 2));
        list.add(new ItemStack(k.alZ, 2));
        list.add(new ItemStack(k.amd, 2));
        list.add(new ItemStack(k.amg, 2));
        list.add(new ItemStack(k.amh, 2));
        list.add(new ItemStack(k.alW));
        list.add(new ItemStack(k.amk));
        list.add(new ItemStack(k.aml));
        list.add(new ItemStack(k.ama));
        list.add(new ItemStack(k.amn));
        list.add(new ItemStack(k.amm));
        list.add(new ItemStack(k.amb));
        list.add(new ItemStack(k.amc));
        return list;
    }

    @Unique
    private ArrayList<ItemStack> decimixin$militaryCrateStack() {
        ArrayList<ItemStack> list = new ArrayList<>(160);
        list.add(new ItemStack(k.amy));
        list.add(new ItemStack(k.ame));
        list.add(new ItemStack(k.amg));
        list.add(new ItemStack(k.alL));
        list.add(new ItemStack(k.alN));
        list.add(new ItemStack(k.alR));
        list.add(new ItemStack(k.apY));
        list.add(new ItemStack(k.and));
        list.add(new ItemStack(k.ane));
        list.add(new ItemStack(k.anj));
        list.add(new ItemStack(k.ank));
        list.add(new ItemStack(k.anm));
        list.add(new ItemStack(k.ann));
        list.add(new ItemStack(k.ano));
        list.add(new ItemStack(k.anp));
        list.add(new ItemStack(k.anq));
        list.add(new ItemStack(k.anr));
        list.add(new ItemStack(k.ans));
        list.add(new ItemStack(k.ant));
        list.add(new ItemStack(k.anJ));
        list.add(new ItemStack(k.anO));
        list.add(new ItemStack(k.anK));
        list.add(new ItemStack(k.anL));
        list.add(new ItemStack(k.anM));
        list.add(new ItemStack(k.anP));
        list.add(new ItemStack(k.anU));
        list.add(new ItemStack(k.anQ));
        list.add(new ItemStack(k.anR));
        list.add(new ItemStack(k.anS));
        list.add(new ItemStack(k.anU));
        list.add(new ItemStack(k.anV));
        list.add(new ItemStack(k.anW));
        list.add(new ItemStack(k.anX));
        list.add(new ItemStack(k.anY));
        list.add(new ItemStack(k.aoa));
        list.add(new ItemStack(k.aoh));
        list.add(new ItemStack(k.aoi));
        list.add(new ItemStack(k.aoj));
        list.add(new ItemStack(k.aok));
        list.add(new ItemStack(k.aol));
        list.add(new ItemStack(k.aob));
        list.add(new ItemStack(k.aoc));
        list.add(new ItemStack(k.aod));
        list.add(new ItemStack(k.aoe));
        list.add(new ItemStack(k.aog));
        list.add(new ItemStack(k.aom));
        list.add(new ItemStack(k.aon));
        list.add(new ItemStack(k.aoo));
        list.add(new ItemStack(k.aop));
        list.add(new ItemStack(k.apc));
        list.add(new ItemStack(k.apd));
        list.add(new ItemStack(k.ape));
        list.add(new ItemStack(k.apf));
        list.add(new ItemStack(k.apg));
        list.add(new ItemStack(k.aph));
        list.add(new ItemStack(k.api));
        list.add(new ItemStack(k.apj));
        list.add(new ItemStack(k.aoY));
        list.add(new ItemStack(k.apb));
        list.add(new ItemStack(k.apa));
        list.add(new ItemStack(k.aoZ));
        list.add(new ItemStack(k.apo));
        list.add(new ItemStack(k.app));
        list.add(new ItemStack(k.avR));
        list.add(new ItemStack(k.avP));
        list.add(new ItemStack(k.avQ));
        list.add(new ItemStack(k.avX));
        list.add(new ItemStack(k.avZ));
        list.add(new ItemStack(k.avY));
        list.add(new ItemStack(k.awa));
        list.add(new ItemStack(k.awc));
        list.add(new ItemStack(k.awb));
        list.add(new ItemStack(k.awd));
        list.add(new ItemStack(k.awe));
        list.add(new ItemStack(k.aqY));
        list.add(new ItemStack(k.aqZ));
        list.add(new ItemStack(k.ara));
        list.add(new ItemStack(k.arb));
        list.add(new ItemStack(k.arc));
        list.add(new ItemStack(k.ard));
        list.add(new ItemStack(k.are));
        list.add(new ItemStack(k.arf));
        list.add(new ItemStack(k.arg));
        list.add(new ItemStack(k.arh));
        list.add(new ItemStack(k.ari));
        list.add(new ItemStack(k.arj));
        list.add(new ItemStack(k.ark));
        list.add(new ItemStack(k.arl));
        list.add(new ItemStack(k.arm));
        list.add(new ItemStack(k.arn));
        list.add(new ItemStack(k.aro));
        list.add(new ItemStack(k.arp));
        list.add(new ItemStack(k.arq));
        list.add(new ItemStack(k.arr));
        list.add(new ItemStack(k.ars));
        list.add(new ItemStack(k.art));
        list.add(new ItemStack(k.aru));
        list.add(new ItemStack(k.arv));
        list.add(new ItemStack(k.arw));
        list.add(new ItemStack(k.arx));
        list.add(new ItemStack(k.ary));
        list.add(new ItemStack(k.arz));
        list.add(new ItemStack(k.arA));
        list.add(new ItemStack(k.arB));
        list.add(new ItemStack(k.arC));
        list.add(new ItemStack(k.arD));
        list.add(new ItemStack(k.arE));
        list.add(new ItemStack(k.arF));
        list.add(new ItemStack(k.arG));
        list.add(new ItemStack(k.arH));
        list.add(new ItemStack(k.arI));
        list.add(new ItemStack(k.arJ));
        list.add(new ItemStack(k.arK));
        list.add(new ItemStack(k.arL));
        list.add(new ItemStack(k.arM));
        list.add(new ItemStack(k.arN));
        list.add(new ItemStack(k.arO));
        list.add(new ItemStack(k.arP));
        list.add(new ItemStack(k.arQ));
        list.add(new ItemStack(k.arR));
        list.add(new ItemStack(k.arS));
        list.add(new ItemStack(k.arT));
        list.add(new ItemStack(k.arU));
        list.add(new ItemStack(k.arW));
        list.add(new ItemStack(k.arX));
        list.add(new ItemStack(k.arY));
        list.add(new ItemStack(k.arZ));
        list.add(new ItemStack(k.asa));
        list.add(new ItemStack(k.asb));
        list.add(new ItemStack(k.asc));
        list.add(new ItemStack(k.asd));
        list.add(new ItemStack(k.ase));
        list.add(new ItemStack(k.asf));
        list.add(new ItemStack(k.asg));
        list.add(new ItemStack(k.ash));
        list.add(new ItemStack(k.asi));
        list.add(new ItemStack(k.asj));
        list.add(new ItemStack(k.ask));
        list.add(new ItemStack(k.asl));
        list.add(new ItemStack(k.asm));
        list.add(new ItemStack(k.asn));
        list.add(new ItemStack(k.aso));
        list.add(new ItemStack(k.asp));
        list.add(new ItemStack(k.asq));
        list.add(new ItemStack(k.asr));
        list.add(new ItemStack(k.ass));
        list.add(new ItemStack(k.ast));
        list.add(new ItemStack(k.asu));
        list.add(new ItemStack(k.asw));
        list.add(new ItemStack(k.asx));
        list.add(new ItemStack(k.asy));
        list.add(new ItemStack(k.asz));
        list.add(new ItemStack(k.asA));
        list.add(new ItemStack(k.asB));
        list.add(new ItemStack(k.asC));
        list.add(new ItemStack(k.asD));
        list.add(new ItemStack(k.asE));
        list.add(new ItemStack(k.asF));
        list.add(new ItemStack(k.asG));
        list.add(new ItemStack(k.asH));
        list.add(new ItemStack(k.asI));
        list.add(new ItemStack(k.asJ));
        list.add(new ItemStack(k.asK));
        list.add(new ItemStack(k.asM));
        list.add(new ItemStack(k.asN));
        list.add(new ItemStack(k.asO));
        list.add(new ItemStack(k.asZ, 2));
        list.add(new ItemStack(k.ata, 2));
        list.add(new ItemStack(k.atb, 2));
        list.add(new ItemStack(k.atc, 2));
        list.add(new ItemStack(k.atd, 2));
        list.add(new ItemStack(k.ate, 2));
        list.add(new ItemStack(k.atf, 2));
        list.add(new ItemStack(k.atg, 2));
        list.add(new ItemStack(k.ath, 2));
        list.add(new ItemStack(k.ati, 2));
        list.add(new ItemStack(k.atj, 2));
        list.add(new ItemStack(k.atk, 2));
        list.add(new ItemStack(k.atl, 2));
        list.add(new ItemStack(k.atm, 2));
        list.add(new ItemStack(k.atn, 2));
        list.add(new ItemStack(k.ato, 2));
        list.add(new ItemStack(k.atp, 2));
        list.add(new ItemStack(k.atq, 2));
        list.add(new ItemStack(k.atr, 2));
        list.add(new ItemStack(k.ats, 2));
        list.add(new ItemStack(k.att, 2));
        list.add(new ItemStack(k.atu, 2));
        list.add(new ItemStack(k.atv, 2));
        list.add(new ItemStack(k.atw, 2));
        list.add(new ItemStack(k.atx, 2));
        list.add(new ItemStack(k.aty, 2));
        list.add(new ItemStack(k.atz, 2));
        list.add(new ItemStack(k.atA, 2));
        list.add(new ItemStack(k.atB, 2));
        list.add(new ItemStack(k.atC, 2));
        list.add(new ItemStack(k.atD, 2));
        list.add(new ItemStack(k.atE, 2));
        list.add(new ItemStack(k.atF, 2));
        list.add(new ItemStack(k.atG, 2));
        list.add(new ItemStack(k.atH, 2));
        list.add(new ItemStack(k.atI, 2));
        list.add(new ItemStack(k.atJ, 2));
        list.add(new ItemStack(k.atK, 2));
        list.add(new ItemStack(k.atL, 2));
        list.add(new ItemStack(k.atM, 2));
        list.add(new ItemStack(k.atN, 2));
        list.add(new ItemStack(k.atO, 2));
        list.add(new ItemStack(k.atP, 2));
        list.add(new ItemStack(k.atQ, 2));
        list.add(new ItemStack(k.atR, 2));
        list.add(new ItemStack(k.atS, 2));
        list.add(new ItemStack(k.atT, 2));
        list.add(new ItemStack(k.atU, 2));
        list.add(new ItemStack(k.atV, 2));
        list.add(new ItemStack(k.atW, 2));
        list.add(new ItemStack(k.atX, 2));
        list.add(new ItemStack(k.atY, 2));
        list.add(new ItemStack(k.atZ, 2));
        list.add(new ItemStack(k.aua, 2));
        list.add(new ItemStack(k.aub, 2));
        list.add(new ItemStack(k.auc, 2));
        list.add(new ItemStack(k.aud, 2));
        list.add(new ItemStack(k.aue, 2));
        list.add(new ItemStack(k.auf, 2));
        list.add(new ItemStack(k.aug, 2));
        list.add(new ItemStack(k.auh, 2));
        list.add(new ItemStack(k.aui, 2));
        list.add(new ItemStack(k.auj, 2));
        list.add(new ItemStack(k.auk, 2));
        list.add(new ItemStack(k.aul, 2));
        list.add(new ItemStack(k.aum, 2));
        list.add(new ItemStack(k.aun, 2));
        list.add(new ItemStack(k.auo, 2));
        list.add(new ItemStack(k.aup, 2));
        list.add(new ItemStack(k.aur, 2));
        list.add(new ItemStack(k.aus, 2));
        list.add(new ItemStack(k.aut, 2));
        list.add(new ItemStack(k.auu, 2));
        list.add(new ItemStack(k.auv, 2));
        list.add(new ItemStack(k.auw, 2));
        list.add(new ItemStack(k.aux, 2));
        list.add(new ItemStack(k.auy, 2));
        list.add(new ItemStack(k.auz, 2));
        list.add(new ItemStack(k.auA, 2));
        list.add(new ItemStack(k.avd, 5));
        list.add(new ItemStack(k.avi, 2));
        list.add(new ItemStack(k.avu, 3));
        list.add(new ItemStack(k.awo));
        list.add(new ItemStack(k.awp));
        list.add(new ItemStack(k.awq));
        list.add(new ItemStack(k.aqP));
        list.add(new ItemStack(k.awl));
        list.add(new ItemStack(k.awj));
        list.add(new ItemStack(k.awm));
        list.add(new ItemStack(k.awn));
        list.add(new ItemStack(k.awk));
        list.add(new ItemStack(k.awf));
        list.add(new ItemStack(k.awi));
        list.add(new ItemStack(k.awg));
        list.add(new ItemStack(k.awh));
        list.add(new ItemStack(k.aws));
        list.add(new ItemStack(k.amC));
        list.add(new ItemStack(k.asS, 2));
        list.add(new ItemStack(k.asU, 2));
        list.add(new ItemStack(k.asT, 2));
        list.add(new ItemStack(k.asV, 2));
        list.add(new ItemStack(k.asW, 3));
        list.add(new ItemStack(k.asX, 3));
        list.add(new ItemStack(k.alJ));
        list.add(new ItemStack(k.alV));
        list.add(new ItemStack(k.awt));
        list.add(new ItemStack(k.awu));
        list.add(new ItemStack(k.awv));
        list.add(new ItemStack(k.aww));
        list.add(new ItemStack(k.awx));
        list.add(new ItemStack(k.awy));
        list.add(new ItemStack(k.awz));
        list.add(new ItemStack(k.apq));
        list.add(new ItemStack(k.apr));
        list.add(new ItemStack(Addon.ghillieUrbanHelm));
        list.add(new ItemStack(Addon.ghillieUrbanVest));
        list.add(new ItemStack(Addon.ghillieUrbanPants));
        list.add(new ItemStack(Addon.ghillieUrbanBoots));
        return list;
    }

    @Unique
    private ArrayList<ItemStack> decimixin$supplyDropStack() {
        ArrayList<ItemStack> list = new ArrayList<>(130);
        list.add(new ItemStack(k.amy));
        list.add(new ItemStack(k.ame));
        list.add(new ItemStack(k.amg));
        list.add(new ItemStack(k.alL));
        list.add(new ItemStack(k.and));
        list.add(new ItemStack(k.ane));
        list.add(new ItemStack(k.anf));
        list.add(new ItemStack(k.anh));
        list.add(new ItemStack(k.anj));
        list.add(new ItemStack(k.ank));
        list.add(new ItemStack(k.aoQ));
        list.add(new ItemStack(k.aoR));
        list.add(new ItemStack(k.aoS));
        list.add(new ItemStack(k.aoT));
        list.add(new ItemStack(k.aoU));
        list.add(new ItemStack(k.aoV));
        list.add(new ItemStack(k.aoW));
        list.add(new ItemStack(k.aoX));
        list.add(new ItemStack(k.awc));
        list.add(new ItemStack(k.awb));
        list.add(new ItemStack(k.awd));
        list.add(new ItemStack(k.awe));
        list.add(new ItemStack(k.arg));
        list.add(new ItemStack(k.arj));
        list.add(new ItemStack(k.arn));
        list.add(new ItemStack(k.arG));
        list.add(new ItemStack(k.aro));
        list.add(new ItemStack(k.arp));
        list.add(new ItemStack(k.arv));
        list.add(new ItemStack(k.arx));
        list.add(new ItemStack(k.asm));
        list.add(new ItemStack(k.arW));
        list.add(new ItemStack(k.arX));
        list.add(new ItemStack(k.asa));
        list.add(new ItemStack(k.arB));
        list.add(new ItemStack(k.asl));
        list.add(new ItemStack(k.arY));
        list.add(new ItemStack(k.art));
        list.add(new ItemStack(k.arf));
        list.add(new ItemStack(k.are));
        list.add(new ItemStack(k.asv));
        list.add(new ItemStack(k.arU));
        list.add(new ItemStack(k.arJ));
        list.add(new ItemStack(k.arK));
        list.add(new ItemStack(k.arI));
        list.add(new ItemStack(k.arL));
        list.add(new ItemStack(k.arR));
        list.add(new ItemStack(k.arS));
        list.add(new ItemStack(k.arT));
        list.add(new ItemStack(k.arV));
        list.add(new ItemStack(k.atw));
        list.add(new ItemStack(k.asP));
        list.add(new ItemStack(k.asQ));
        list.add(new ItemStack(k.asR));
        list.add(new ItemStack(k.atb, 3));
        list.add(new ItemStack(k.atj, 3));
        list.add(new ItemStack(k.atn, 3));
        list.add(new ItemStack(k.atF, 3));
        list.add(new ItemStack(k.ato, 3));
        list.add(new ItemStack(k.atp, 3));
        list.add(new ItemStack(k.att, 3));
        list.add(new ItemStack(k.atv, 3));
        list.add(new ItemStack(k.auh, 3));
        list.add(new ItemStack(k.atR, 3));
        list.add(new ItemStack(k.atS, 3));
        list.add(new ItemStack(k.atV, 3));
        list.add(new ItemStack(k.atA, 3));
        list.add(new ItemStack(k.aug, 3));
        list.add(new ItemStack(k.atT, 3));
        list.add(new ItemStack(k.ati, 3));
        list.add(new ItemStack(k.atO, 2));
        list.add(new ItemStack(k.atN, 3));
        list.add(new ItemStack(k.auq));
        list.add(new ItemStack(k.atI, 4));
        list.add(new ItemStack(k.atJ, 4));
        list.add(new ItemStack(k.atH, 2));
        list.add(new ItemStack(k.atK, 2));
        list.add(new ItemStack(k.atP, 4));
        list.add(new ItemStack(k.atQ, 2));
        list.add(new ItemStack(k.atw, 3));
        list.add(new ItemStack(k.avd, 5));
        list.add(new ItemStack(k.ave));
        list.add(new ItemStack(k.avf));
        list.add(new ItemStack(k.avu, 3));
        list.add(new ItemStack(k.asS));
        list.add(new ItemStack(k.asU));
        list.add(new ItemStack(k.asT));
        list.add(new ItemStack(k.asV));
        list.add(new ItemStack(k.amV));
        list.add(new ItemStack(k.amW));
        list.add(new ItemStack(k.amX));
        list.add(new ItemStack(k.alQ));
        list.add(new ItemStack(k.asL));
        list.add(new ItemStack(k.awr));
        list.add(new ItemStack(k.anT));
        list.add(new ItemStack(k.anZ));
        list.add(new ItemStack(k.aof));
        list.add(new ItemStack(Addon.marineBlackMedical));
        list.add(new ItemStack(Addon.thermalScope));
        return list;
    }
    @Overwrite
    public deci.aB.c c(Block var1) {
        return this.afq.get(var1);
    }
}